"""add user_name to transcript_segments and update user_id type

Revision ID: 302fbbd7ed0f
Revises: 6f1a8b9c1d2e
Create Date: 2026-05-14 16:00:30.305750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '302fbbd7ed0f'
down_revision: Union[str, Sequence[str], None] = '6f1a8b9c1d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcript_segments', sa.Column('user_name', sa.String(), nullable=True))
    op.alter_column('transcript_segments', 'user_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='user_id::uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transcript_segments', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using='user_id::varchar')
    op.drop_column('transcript_segments', 'user_name')
    # ### end Alembic commands ###
