"""Add ScheduledMeeting table

Revision ID: 341e24a2c88e
Revises: 9e76026e31c8
Create Date: 2026-05-21 08:56:28.249160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '341e24a2c88e'
down_revision: Union[str, Sequence[str], None] = '9e76026e31c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_meetings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('scheduled_date', sa.String(), nullable=False),
    sa.Column('scheduled_start_time', sa.String(), nullable=False),
    sa.Column('expected_duration_min', sa.Integer(), nullable=True),
    sa.Column('objectives', sa.String(), nullable=True),
    sa.Column('participants', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduled_meetings')
    # ### end Alembic commands ###
