"""add role to meeting_participant

Revision ID: 6bc476c36ffd
Revises: 302fbbd7ed0f
Create Date: 2026-05-14 18:03:44.441717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bc476c36ffd'
down_revision: Union[str, Sequence[str], None] = '302fbbd7ed0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting_participants', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting_participants', 'role')
    # ### end Alembic commands ###
