"""expand_meeting_analysis_and_add_action_items_decisions

Revision ID: 76dce0e3c602
Revises: a343c508c2d9
Create Date: 2026-05-19 22:52:21.718255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76dce0e3c602'
down_revision: Union[str, Sequence[str], None] = 'a343c508c2d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('meeting_analysis', sa.Column('mode', sa.String(), nullable=True))
    op.add_column('meeting_analysis', sa.Column('insights', sa.JSON(), nullable=True))
    op.drop_column('meeting_analysis', 'action_items')
    op.add_column('meetings', sa.Column('mode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'mode')
    op.add_column('meeting_analysis', sa.Column('action_items', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('meeting_analysis', 'insights')
    op.drop_column('meeting_analysis', 'mode')
    op.drop_table('decisions')
    op.drop_table('action_items')
    # ### end Alembic commands ###
