"""add_join_code

Revision ID: a492985fd2da
Revises: b0640da617d9
Create Date: 2026-06-02 10:49:45.391419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a492985fd2da'
down_revision: Union[str, Sequence[str], None] = 'b0640da617d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('join_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_meetings_join_code'), 'meetings', ['join_code'], unique=True)
    op.add_column('scheduled_meetings', sa.Column('join_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_scheduled_meetings_join_code'), 'scheduled_meetings', ['join_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_meetings_join_code'), table_name='scheduled_meetings')
    op.drop_column('scheduled_meetings', 'join_code')
    op.drop_index(op.f('ix_meetings_join_code'), table_name='meetings')
    op.drop_column('meetings', 'join_code')
    # ### end Alembic commands ###
